on: [push]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    name: Build Interpreters (Linux)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install tcl8.6-dev
      - name: Build
        run: cd linux && ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-linux
          path: linux/python-appimage/linux_*.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: linux/python-appimage/linux_*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_macos:
    runs-on: macos-latest
    name: Build Interpreters (macOS)
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cd macos && ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-macos
          path: macos/relocatable-python/darwin_*.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: macos/relocatable-python/darwin_*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
